// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBctGdWGBuXf4hdV_-rg8yD1XDVW2EGCew',
    appId: '1:284225918938:web:7c50a1186c8d28c848d2e3',
    messagingSenderId: '284225918938',
    projectId: 'task-60403',
    authDomain: 'task-60403.firebaseapp.com',
    storageBucket: 'task-60403.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiuCWHwdQ973VCjBTHXgPN8PTyaROESpU',
    appId: '1:284225918938:android:a47b9719b6d965bc48d2e3',
    messagingSenderId: '284225918938',
    projectId: 'task-60403',
    storageBucket: 'task-60403.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlNYsJCd-zFb1R-cYSm2v4ksak-hvyTmM',
    appId: '1:284225918938:ios:ba0935ab1c5b501948d2e3',
    messagingSenderId: '284225918938',
    projectId: 'task-60403',
    storageBucket: 'task-60403.firebasestorage.app',
    iosBundleId: 'com.example.taskDashboard',
  );
}
